In [10]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(r"C:\Users\tanma\Downloads\DATASETS\Stock_data\DIS.csv")

In [4]:
df.head()

       Date      Close       High        Low       Open    Volume
0  1/3/2000  22.583426  22.630672  21.733004  22.110969   8402230
1  1/4/2000  23.906307  24.095291  22.677919  22.677919  16051191
2  1/5/2000  24.898470  25.040209  23.906311  23.906311  19823822
3  1/6/2000  23.906307  25.040204  23.906307  24.898466   7903193
4  1/7/2000  23.528339  24.284270  23.292110  23.906305   6773543

In [5]:
df.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6559 entries, 0 to 6558
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6559 non-null   object
 1   Close   6559 non-null   float64
 2   High    6559 non-null   float64
 3   Low     6559 non-null   float64
 4   Open    6559 non-null   float64
 5   Volume  6559 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 307.6+ KB

In [12]:
df.shape

(6559, 6)

In [47]:
# 1. Create lag features
df['Close_lag1'] = df['Close'].shift(1)
df['Close_lag2'] = df['Close'].shift(2)

# 2. Create target (future prediction)
df['Target'] = df['Close'].shift(-1)

# 3. Remove NaN values
df = df.dropna()

# 4. Define features & target
x = df[['Close_lag1', 'Close_lag2', 'Volume']]
y = df['Target']

C:\Users\tanma\AppData\Local\Temp\ipykernel_20568\1746127151.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Close_lag1'] = df['Close'].shift(1)
C:\Users\tanma\AppData\Local\Temp\ipykernel_20568\1746127151.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Close_lag2'] = df['Close'].shift(2)
C:\Users\tanma\AppData\Local\Temp\ipykernel_20568\1746127151.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Target'] = df['Close'].shift(-1)

In [53]:
x

      Close_lag1  Close_lag2    Volume
4      23.906307   24.898470   6773543
5      23.528339   23.906307  33965839
6      27.119009   23.528339  20134820
7      27.402479   27.119009  13100963
8      25.465416   27.402479   8732387
...          ...         ...       ...
6552  113.190002  110.339996  12437700
6553  113.209999  113.190002  10819800
6554  110.980003  113.209999   8859800
6555  111.309998  110.980003   8956900
6556  110.610001  111.309998   9016600

[6553 rows x 3 columns]

In [48]:
# train test split 
# we use this method because if we use the train_test_split than it shuffles data randomly and the future data go into the trining part and the past data into the testing part
x_train, x_test = x[:int(0.8*len(x))], x[int(0.8*len(x)):]
y_train, y_test = y[:int(0.8*len(y))], y[int(0.8*len(y)):]

In [49]:
# Here we are shifting the data because "To predict today’s price, look at previous days’ prices"
df['Close_lag1'] = df['Close'].shift(1)
df['Close_lag2'] = df['Close'].shift(2)

### Linear Regression Model

In [50]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [51]:
y_pred = lr.predict(x_test)

In [52]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mae)
print("MSE:",mse)
print("R2 Score:", r2)
print("RMSE:", rmse)

MAE: 2.1849654818865605
MSE: 9.989282825696828
R2 Score: 0.9897579288583515
RMSE: 3.1605826718655576

### Random forest Regressor

In [77]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_estimators=100,max_depth = 10, random_state=42)
rfr.fit(x_train,y_train)

RandomForestRegressor(max_depth=10, random_state=42)

In [78]:
y_pred = rfr.predict(x_test)

In [79]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mae)
print("MSE:",mse)
print("R2 Score:", r2)
print("RMSE:", rmse)

MAE: 7.161025083878591
MSE: 174.74767104166133
R2 Score: 0.8208301727084946
RMSE: 13.219215976814258