In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression

In [4]:
df = pd.read_csv(r"C:\Users\tanma\Downloads\DATASETS\students_dataset\student_exam_performance_dataset.csv")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  10000 non-null  object
 1   gender                      10000 non-null  object
 2   age                         10000 non-null  int64
 3   parental_education          10000 non-null  object
 4   family_income               10000 non-null  object
 5   internet_access             10000 non-null  object
 6   study_environment           10000 non-null  object
 7   study_hours_per_day         10000 non-null  float64
 8   attendance_rate             10000 non-null  float64
 9   sleep_hours                 10000 non-null  float64
 10  social_media_hours          10000 non-null  float64
 11  assignment_completion_rate  10000 non-null  float64
 12  participation_score         10000 non-null  float64
 13  online_courses_completed    10000 non-null  int64
 14  tutoring                    10000 non-null  object
 15  math_score                  10000 non-null  float64
 16  reading_score               10000 non-null  float64
 17  writing_score               10000 non-null  float64
 18  science_score               10000 non-null  float64
 19  final_exam_score            10000 non-null  float64
 20  previous_gpa                10000 non-null  float64
 21  pass_fail                   10000 non-null  object
 22  grade_category              10000 non-null  object
dtypes: float64(12), int64(2), object(9)
memory usage: 1.8+ MB

In [7]:
df.isnull().sum()

student_id                    0
gender                        0
age                           0
parental_education            0
family_income                 0
internet_access               0
study_environment             0
study_hours_per_day           0
attendance_rate               0
sleep_hours                   0
social_media_hours            0
assignment_completion_rate    0
participation_score           0
online_courses_completed      0
tutoring                      0
math_score                    0
reading_score                 0
writing_score                 0
science_score                 0
final_exam_score              0
previous_gpa                  0
pass_fail                     0
grade_category                0
dtype: int64

In [11]:
df

,student_id,gender,age,parental_education,family_income,internet_access,study_environment,study_hours_per_day,attendance_rate,sleep_hours,...,online_courses_completed,tutoring,math_score,reading_score,writing_score,science_score,final_exam_score,previous_gpa,pass_fail,grade_category
0,S00001,Male,17,High School,Medium,Yes,Quiet,2.98,96.5,6.05,...,1,Yes,42.8,62.4,54.8,51.8,49.1,2.44,Fail,F
1,S00002,Female,18,High School,Low,Yes,Quiet,4.45,95.7,6.96,...,0,Yes,77.9,73.5,64.4,61.6,70.1,2.79,Pass,C
2,S00003,Male,17,High School,Medium,No,Quiet,3.75,76.0,7.02,...,4,Yes,53.5,38.3,36.3,47.1,42.2,1.49,Fail,F
3,S00004,Male,18,Bachelor,Medium,Yes,Quiet,2.03,72.6,6.23,...,4,No,28.3,23.5,32.0,39.0,31.9,1.34,Fail,F
4,S00005,Male,18,Bachelor,Medium,Yes,Quiet,5.14,87.3,8.54,...,0,No,74.7,54.9,73.6,55.5,66.4,2.60,Pass,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,S09996,Female,15,Master,High,Yes,Moderate,3.80,83.1,7.48,...,1,No,44.2,38.2,38.5,39.0,41.9,1.54,Fail,F
9996,S09997,Male,15,High School,Medium,Yes,Quiet,2.46,68.0,6.76,...,3,No,56.8,46.2,50.6,34.9,47.5,1.49,Fail,F
9997,S09998,Female,15,High School,Low,Yes,Moderate,5.08,76.0,6.90,...,2,No,67.4,50.5,63.7,83.3,64.2,2.38,Pass,D
9998,S09999,Female,18,Bachelor,Medium,Yes,Moderate,1.56,91.0,7.13,...,1,No,35.4,35.5,46.8,47.2,44.3,1.45,Fail,F
9999,S10000,Male,17,High School,Low,Yes,Noisy,3.63,100.0,5.42,...,0,No,66.7,61.6,60.3,60.4,59.6,2.24,Pass,D

In [18]:
X = df.drop(["student_id","parental_education","family_income","grade_category","pass_fail"],axis = 1)
y = df["pass_fail"]

In [26]:
X.head()

,gender,age,internet_access,study_environment,study_hours_per_day,attendance_rate,sleep_hours,social_media_hours,assignment_completion_rate,participation_score,online_courses_completed,tutoring,math_score,reading_score,writing_score,science_score,final_exam_score,previous_gpa
0,Male,17,Yes,Quiet,2.98,96.5,6.05,0.1,80.5,68.7,1,Yes,42.8,62.4,54.8,51.8,49.1,2.44
1,Female,18,Yes,Quiet,4.45,95.7,6.96,2.9,70.9,92.6,0,Yes,77.9,73.5,64.4,61.6,70.1,2.79
2,Male,17,No,Quiet,3.75,76.0,7.02,2.4,77.6,45.8,4,Yes,53.5,38.3,36.3,47.1,42.2,1.49
3,Male,18,Yes,Quiet,2.03,72.6,6.23,3.5,63.5,72.9,4,No,28.3,23.5,32.0,39.0,31.9,1.34
4,Male,18,Yes,Quiet,5.14,87.3,8.54,2.1,71.8,55.7,0,No,74.7,54.9,73.6,55.5,66.4,2.60

In [21]:
df.shape

(10000, 23)

In [47]:
# Encoding 
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

X = pd.get_dummies(X)

In [46]:
X.head()

,age,study_hours_per_day,attendance_rate,sleep_hours,social_media_hours,assignment_completion_rate,participation_score,online_courses_completed,math_score,reading_score,...,previous_gpa,gender_Female,gender_Male,internet_access_No,internet_access_Yes,study_environment_Moderate,study_environment_Noisy,study_environment_Quiet,tutoring_No,tutoring_Yes
0,17,2.98,96.5,6.05,0.1,80.5,68.7,1,42.8,62.4,...,2.44,False,True,False,True,False,False,True,False,True
1,18,4.45,95.7,6.96,2.9,70.9,92.6,0,77.9,73.5,...,2.79,True,False,False,True,False,False,True,False,True
2,17,3.75,76.0,7.02,2.4,77.6,45.8,4,53.5,38.3,...,1.49,False,True,True,False,False,False,True,False,True
3,18,2.03,72.6,6.23,3.5,63.5,72.9,4,28.3,23.5,...,1.34,False,True,False,True,False,False,True,True,False
4,18,5.14,87.3,8.54,2.1,71.8,55.7,0,74.7,54.9,...,2.60,False,True,False,True,False,False,True,True,False

In [50]:
x_train,x_test,y_train,y_test = train_test_split(
    X,y,test_size = 0.2,random_state = 42
)

In [51]:
#Linear regression 

lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [63]:
from sklearn.metrics import r2_score,mean_absolute_error, mean_squared_error,root_mean_squared_error
y_pred = lr.predict(x_test)
r2 = r2_score(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
RMSE = root_mean_squared_error(y_test,y_pred)
print("r2 score",r2)
print("MAE",mae)
print("MSE",mse)
print("RMSE",RMSE)

r2 score 0.630440632664528
MAE 0.2651112755139579
MSE 0.09193713160888208
RMSE 0.3032113645773886

In [65]:
#Ridge regression
from sklearn.linear_model import Ridge
RIG_model = Ridge(alpha=1.0)
RIG_model.fit(x_train,y_train)

Ridge()

In [67]:
ypred = RIG_model.predict(x_test)
r2 = r2_score(y_test,ypred)
mae = mean_absolute_error(y_test,ypred)
mse = mean_squared_error(y_test,ypred)
RMSE = root_mean_squared_error(y_test,ypred)
print("r2 score",r2)
print("MAE",mae)
print("MSE",mse)
print("RMSE",RMSE)

r2 score 0.6304407878917597
MAE 0.2651114147291789
MSE 0.09193709299222746
RMSE 0.30321130089795045

In [68]:
# lasso regression
from sklearn import linear_model
lasso = linear_model.Lasso(alpha=0.1)
lasso.fit(x_train,y_train)

Lasso(alpha=0.1)

In [69]:
ypred =lasso.predict(x_test)
r2 = r2_score(y_test,ypred)
mae = mean_absolute_error(y_test,ypred)
mse = mean_squared_error(y_test,ypred)
RMSE = root_mean_squared_error(y_test,ypred)
print("r2 score",r2)
print("MAE",mae)
print("MSE",mse)
print("RMSE",RMSE)

r2 score 0.6297691714880991
MAE 0.26664567177727005
MSE 0.09210417436304817
RMSE 0.3034866955288949