In [3]:
#import libraries
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
# load datasets
df = pd.read_csv(r"C:\Users\tanma\Downloads\DATASETS\ipl 2008-2024\ipl_2008_2024_complete.csv")

In [6]:
df.head()

,match_id,innings,total_runs,extras,wickets,balls_bowled,boundaries_4,boundaries_6,dot_balls,batting_team,...,date,venue,city,toss_winner,toss_decision,winner,player_of_match,method,season,toss_win_match_win
0,335982,1,205,17,3,124,15,14,45,Kolkata Knight Riders,...,2008-04-18,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,BB McCullum,NaN,2008.0,0.0
1,335982,2,63,19,10,101,3,3,65,Royal Challengers Bangalore,...,2008-04-18,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,BB McCullum,NaN,2008.0,0.0
2,335983,1,234,6,5,124,20,16,39,Chennai Super Kings,...,2008-04-19,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings,bat,Chennai Super Kings,MEK Hussey,NaN,2008.0,1.0
3,335983,2,196,11,4,124,18,9,33,Kings XI Punjab,...,2008-04-19,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings,bat,Chennai Super Kings,MEK Hussey,NaN,2008.0,1.0
4,335984,1,122,7,8,122,14,3,60,Rajasthan Royals,...,2008-04-19,Feroz Shah Kotla,Delhi,Rajasthan Royals,bat,Delhi Daredevils,MF Maharoof,NaN,2008.0,0.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2217 entries, 0 to 2216
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   match_id            2217 non-null   int64
 1   innings             2217 non-null   int64
 2   total_runs          2217 non-null   int64
 3   extras              2217 non-null   int64
 4   wickets             2217 non-null   int64
 5   balls_bowled        2217 non-null   int64
 6   boundaries_4        2217 non-null   int64
 7   boundaries_6        2217 non-null   int64
 8   dot_balls           2217 non-null   int64
 9   batting_team        2217 non-null   object
 10  bowling_team        2217 non-null   object
 11  dot_ball_pct        2217 non-null   float64
 12  extras_pct          2217 non-null   float64
 13  run_rate            2217 non-null   float64
 14  powerplay_runs      2217 non-null   int64
 15  powerplay_wickets   2217 non-null   int64
 16  death_over_runs     2217 non-null   float64
 17  death_over_wickets  2217 non-null   float64
 18  date                2217 non-null   object
 19  venue               2217 non-null   object
 20  city                2107 non-null   object
 21  toss_winner         2217 non-null   object
 22  toss_decision       2217 non-null   object
 23  winner              2152 non-null   object
 24  player_of_match     2210 non-null   object
 25  method              42 non-null     object
 26  season              2217 non-null   float64
 27  toss_win_match_win  2217 non-null   float64
dtypes: float64(7), int64(11), object(10)
memory usage: 485.1+ KB

In [11]:
df.head()

,match_id,innings,total_runs,extras,wickets,balls_bowled,boundaries_4,boundaries_6,dot_balls,batting_team,...,date,venue,city,toss_winner,toss_decision,winner,player_of_match,method,season,toss_win_match_win
0,335982,1,205,17,3,124,15,14,45,Kolkata Knight Riders,...,2008-04-18,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,1,Kolkata Knight Riders,BB McCullum,NaN,2008.0,0.0
1,335982,2,63,19,10,101,3,3,65,Royal Challengers Bangalore,...,2008-04-18,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,1,Kolkata Knight Riders,BB McCullum,NaN,2008.0,0.0
2,335983,1,234,6,5,124,20,16,39,Chennai Super Kings,...,2008-04-19,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings,0,Chennai Super Kings,MEK Hussey,NaN,2008.0,1.0
3,335983,2,196,11,4,124,18,9,33,Kings XI Punjab,...,2008-04-19,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings,0,Chennai Super Kings,MEK Hussey,NaN,2008.0,1.0
4,335984,1,122,7,8,122,14,3,60,Rajasthan Royals,...,2008-04-19,Feroz Shah Kotla,Delhi,Rajasthan Royals,0,Delhi Daredevils,MF Maharoof,NaN,2008.0,0.0

In [107]:
# feature engineering 
df['team_avg_score'] = df.groupby('batting_team')['total_runs'].transform('mean')
df['venue_avg_score'] = df.groupby('venue')['total_runs'].transform('mean')
df['toss_win'] = (df['toss_winner'] == df['batting_team']).astype(int)
df['season_avg_score'] = df.groupby('season')['total_runs'].transform('mean')
df['team_venue_avg'] = df.groupby(['batting_team','venue'])['total_runs'].transform('mean')
df['city_avg_score'] = df.groupby('city')['total_runs'].transform('mean')
df['city_avg_score'].fillna(df['venue_avg_score'], inplace=True)

C:\Users\tanma\AppData\Local\Temp\ipykernel_22716\1317523628.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city_avg_score'].fillna(df['venue_avg_score'], inplace=True)

In [108]:
#encoding 
from sklearn.preprocessing import LabelEncoder

X_cat = pd.get_dummies(df[['batting_team','venue','city','toss_decision']], drop_first=True)
X_num = df[['team_avg_score','venue_avg_score','season_avg_score',
            'team_venue_avg','city_avg_score','toss_win']]

X = pd.concat([X_cat, X_num], axis=1)

y = df['total_runs']

In [109]:
#train_test_split

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(
    X,y,test_size = 42,random_state = 42
)

In [110]:
X.isnull().sum()

toss_decision                    0
batting_team_Deccan Chargers     0
batting_team_Delhi Capitals      0
batting_team_Delhi Daredevils    0
batting_team_Gujarat Lions       0
                                ..
venue_avg_score                  0
season_avg_score                 0
team_venue_avg                   0
city_avg_score                   0
toss_win                         0
Length: 117, dtype: int64

# model training
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(x_train,y_train)

In [112]:
y_pred = linreg.predict(x_test)

In [113]:
from sklearn.metrics import mean_absolute_error, r2_score
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 16.003778366815474
R2 Score: 0.5586151066563281

In [114]:
# Random forest Regressor 
from sklearn.ensemble import RandomForestRegressor
RfR = RandomForestRegressor(n_estimators = 300, random_state=42)
RfR.fit(x_train, y_train)

RandomForestRegressor(n_estimators=300, random_state=42)

In [115]:
Y_pred = linreg.predict(x_test)

In [116]:
print("MAE:", mean_absolute_error(y_test, Y_pred))
print("R2 Score:", r2_score(y_test, Y_pred))

MAE: 16.003778366815474
R2 Score: 0.5586151066563281

In [118]:
#XGBoost regressor model
from xgboost import XGBRegressor

model = XGBRegressor(n_estimators=300, learning_rate=0.05)
model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [119]:
Y_Pred = linreg.predict(x_test)

In [120]:
print("MAE:", mean_absolute_error(y_test, Y_Pred))
print("R2 Score:", r2_score(y_test, Y_Pred))

MAE: 16.003778366815474
R2 Score: 0.5586151066563281

In [ ]:
# The feature set captured mostly linear relationships, so even advanced models
# like XGBoost couldn’t improve further. Additional gains require richer features like recent form or match-level granularity.