In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(r"C:\Users\tanma\Downloads\DATASETS\cars_dataset\car_price_dataset.csv")

In [3]:
df.isnull().sum()

Car_ID          0
Brand           0
Model_Year      0
Engine_Size     0
Fuel_Type       0
Transmission    0
Mileage         0
Doors           0
Owner_Count     0
Horsepower      0
Price           0
dtype: int64

In [4]:
df.head()

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35

In [5]:
df.shape

(2000, 11)

In [6]:
df = df.drop("Car_ID",axis =1)

In [7]:
df

,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
4,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35
...,...,...,...,...,...,...,...,...,...,...
1995,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35
1996,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80
1997,Hyundai,2022,4.1,Diesel,Manual,104372,4,3,191,55714.40
1998,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65
1999,Honda,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70

In [8]:
# Encoding of the categorical columns by using one hot encoding 
x = df.drop("Price",axis =1)
y =df["Price"]
x = pd.get_dummies(x,drop_first=True)

In [9]:
x

,Model_Year,Engine_Size,Mileage,Doors,Owner_Count,Horsepower,Brand_Ford,Brand_Honda,Brand_Hyundai,Brand_Tesla,Brand_Toyota,Fuel_Type_Electric,Fuel_Type_Hybrid,Fuel_Type_Petrol,Transmission_Manual
0,2023,1.2,180635,4,3,82,True,False,False,False,False,False,True,False,True
1,2018,3.2,35628,2,4,259,False,False,True,False,False,True,False,False,True
2,2008,2.2,74672,3,2,333,False,False,False,False,False,False,False,False,True
3,2017,2.2,51246,4,4,381,False,False,True,False,False,False,False,True,False
4,2012,2.4,147233,3,4,290,False,False,True,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2023,4.5,155033,2,3,310,False,False,True,False,False,False,False,False,True
1996,2023,1.4,25044,2,4,271,False,False,False,False,True,False,False,True,True
1997,2022,4.1,104372,4,3,191,False,False,True,False,False,False,False,False,True
1998,2020,4.4,158047,4,1,186,False,False,False,False,False,False,False,False,False
1999,2012,1.7,19706,3,1,165,False,True,False,False,False,True,False,False,False

In [10]:
# split the data 
x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state = 42
)

### Linear Regression Model

In [11]:
# linear regression
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [12]:
y_pred = lr.predict(x_test)

In [13]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
r2 = r2_score(y_pred,y_test)
MAE = mean_absolute_error(y_pred,y_test)
MSE = mean_squared_error(y_pred,y_test)
rmse = mean_squared_error(y_pred,y_test,squared=False)
print("R2 score is :",r2)
print("mean_absolute_error is:",MAE)
print("mean_squared_error is :",MSE)
print("RMSE :",rmse)

R2 score is : 0.9645203377203057
mean_absolute_error is: 1442.3912465894693
mean_squared_error is : 2766510.356305506
RMSE : 1663.2830054760693

C:\Users\tanma\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

### XGBoost Model

In [14]:
# XGBoost 
from xgboost import XGBRegressor
xgb = XGBRegressor(n_estimators=200,max_depth=5,random_state=42)

In [15]:
xgb.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [16]:
y_pred = xgb.predict(x_test)

In [17]:
r2 = r2_score(y_pred,y_test)
MAE = mean_absolute_error(y_pred,y_test)
MSE = mean_squared_error(y_pred,y_test)
rmse = mean_squared_error(y_pred,y_test,squared=False)
print("R2 score is :",r2)
print("mean_absolute_error is:",MAE)
print("mean_squared_error is :",MSE)
print("RMSE :",rmse)

R2 score is : 0.9273395770262002
mean_absolute_error is: 1886.9344072265624
mean_squared_error is : 5327629.435918075
RMSE : 2308.165816382799

C:\Users\tanma\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [18]:
# hyperparameter tuning in the XGBoost 
from sklearn.model_selection import GridSearchCV

In [19]:
param_grid = {
    'n_estimators': [100, 300, 500],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [3, 4, 5],
    'subsample': [0.8, 0.9, 1]
}

In [20]:
XGB = XGBRegressor(random_state=42)

grid = GridSearchCV(
    estimator=XGB,
    param_grid=param_grid,
    cv=5
)

grid.fit(x_train, y_train)

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    importance_type=None,
                                    interaction_constraints=None...
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             param_grid={'learning_rate': [0.01, 0.05, 0.1],
                         'max_depth': [3, 4, 5],
                         'n_estimators': [100, 300, 500],
                         'subsample': [0.8, 0.9, 1]})

In [21]:
print("Best Parameters:", grid.best_params_)

Best Parameters: {'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 300, 'subsample': 0.8}

In [23]:
best_model = grid.best_estimator_

y_pred = best_model.predict(x_test)

In [24]:
r2 = r2_score(y_pred,y_test)
MAE = mean_absolute_error(y_pred,y_test)
MSE = mean_squared_error(y_pred,y_test)
rmse = mean_squared_error(y_pred,y_test,squared=False)
print("R2 score is :",r2)
print("mean_absolute_error is:",MAE)
print("mean_squared_error is :",MSE)
print("RMSE :",rmse)

R2 score is : 0.9525758781400642
mean_absolute_error is: 1550.9236054687499
mean_squared_error is : 3476911.154254464
RMSE : 1864.64772926536

C:\Users\tanma\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(